version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    volumes:
      - ../:/workspaces/sql-exam:Z,cached
    network_mode: service:db
    security_opt:
      - label=disable
    userns_mode: "keep-id"
    command: sleep infinity

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_exam_db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ExamPassword!123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: